### PR TITLE
Adds startupProbe for Kong Ingress Controller

### PR DESCRIPTION
**Pull request by danibaeyens**
- **This repository allows merge commits, if you're creating a Release, make sure to select 'Squash and merge'**
- **When merging subtree updates, it is important to select 'Create a merge commit' when merging.**

I'm not sure how you really manage your app versions vs upstream ones. Any comment will be welcomed.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Hello,

thanks for your contribution! I don't know why the CircleCI jobs do not run, I'll try to push some changes to your branch.

**Comment by ubergesundheit** [comment]
Looks like tests still work :+1: 

I've pushed the following changes to your branch:

- Restrict the Chart to be installed on clusters running 1.20 and above
- Update the values schema

If you're fine with the changes, this would be ready from my side.

**Review by ubergesundheit — APPROVED** [review]
LGTM

**Comment by ubergesundheit** [comment]
I'll craft a patch release now.

**Comment by danibaeyens** [comment]
Amazing! Thanks a lot! :)

**Comment by ubergesundheit** [comment]
Actually, this will be a minor. :)

**Pull request merged**
