### PR TITLE
Upgrade kong-ingress-controller to 2.7.0

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR updates the used kong kubernetes ingress controller container image tag to use the latest 2.7.0.

### CODE REVIEW

**Comment by webwurst** [comment]
Maybe we should explicitly quote this from upstream in our changelog?
> These versions are EOL, and we advise users to upgrade to Kubernetes 1.22 or later before upgrading to KIC 2.6+ or Kong 3.0+.

**Comment by ubergesundheit** [comment]
Maybe even better to change the required kubernetes version in the Chart.yaml and also simply saying stuff below 1.22 is not supported any more. Also adding something to the Changelog :+1:

**Review by webwurst — APPROVED** [review]

**Comment by Gacko** [comment]
No chart changes?

**Comment by ubergesundheit** [comment]
No, only the container image tag is new

**Pull request merged**
