### PR TITLE
Split registry value to allow switching registry

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

Currently we deploy to China with quay registry which is slow.

### CODE REVIEW

**Review by ced0ps — APPROVED** [review]
Not sure about the double quotes to single quotes conversion considering the next upstream chart sync but LGTM

**Comment by jgsqware** [comment]
it's my f*** linter in vscode that mix everything
let me try to avoid this

**Comment by jgsqware** [comment]
@ced0ps better?

**Review by ced0ps — APPROVED** [review]
LGTM

**Pull request merged**
