### PR TITLE
Add Version matrix to README

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR is adding a version matrix to the README

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
Can we also show GS version?

**Comment by ubergesundheit** [comment]
> Can we also show GS version?

First column is GS version

**Comment by JosephSalisbury** [comment]
okay, then can we make that a bit clearer that it's a giant swarm version, and add the upstream chart version? :D

**Comment by ubergesundheit** [comment]
> okay, then can we make that a bit clearer that it's a giant swarm version, and add the upstream chart version? :D

yes

**Review by JosephSalisbury — APPROVED** [review]
<3

**Pull request merged**
