### PR TITLE
Correct Prometheus service discovery

### PR DESCRIPTION
**Pull request by glitchcrab**
This PR removes the service and annotates the pods directly. This is because metrics are per Kong pod, so scraping the service won't work when there are more than 1 Kong pods.

### CODE REVIEW

**Comment by sslavic** [comment]
@glitchcrab in nginx we needed both:
- Pod metrics ports discovery for our CP Prometheus + PCC
- optional metrics Service for customer monitoring via Prometheus Operator managed Prometheus 

metrics Service is not used directly by Prometheus, from it's selector definition and metrics port all matching Pods get registered as Endpoints, which then ServiceMonitor definition can target
I see this chart has ServiceMonitor definition, so for Prometheus Operator support. See docs https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources

You know better what are plans for Kong, just suggesting to consider keeping both options for some time, until we all converge to Prometheus Operator only - AFAIK that's the plan for CP Prometheus future.

**Comment by glitchcrab** [comment]
@sslavic the reason for removing the service is due to a mis-understanding on my part when I first added it. Kong metrics aren't cluster-wide - they're specific to each replica. Because of this we have to scrape the Kong pods directly as scraping the service means we only get metrics for a single replica.

**Comment by glitchcrab** [comment]
OK, so following on from @sslavic's comment above, I've retained the metrics service as a headless service (as we would only care about the endpoints behind it), and I've removed the prometheus annotations from it to ensure it isn't accidentally scraped by any customer prometheuses.

**Comment by glitchcrab** [comment]
I'm gonna go ahead and merge this as I've tested it and it looks good.

**Pull request merged**
